language: python
python:
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build
# command to install dependencies
install:
   - sudo apt-get update
   - sudo apt-get install -y nasm
#   - pip install -r requirements.txt
# command to run tests
script:
  - make test

